config/routes.rb
Rails.application.routes.draw do
  # # See all restaurants ✅
  # get "restaurants", to: "restaurants#index"

  # # Show the restaurant form
  # get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  # # Create a restaurant
  # post "restaurants", to: "restaurants#create"

  # # See details about one restaurant
  # get "restaurants/:id", to: "restaurants#show", as: :restaurant

  # # Update a restaurant
  # get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant
  # patch "restaurants/:id", to: "restaurants#update"

  # # Destroy a restaurant
  # delete "restaurants/:id", to: "restaurants#destroy"

  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def edit; end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord546</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container col-6 text-center">
  <h1>Edit <%= @restaurant.name %></h1>

  <%= render "form", restaurant: @restaurant %>
</div>

app/views/restaurants/index.html.erb
<h1>All our restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
    <%= link_to restaurant.name, restaurant_path(restaurant) %> -
    <%= link_to "Edit", edit_restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<div class="container col-6 text-center">
  <h1>Create a new Restaurant</h1>

  <%= render "form", restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.rating %></p>
<p><%= @restaurant.address %></p>

<%= link_to "Edit", edit_restaurant_path(@restaurant) %>

<%= link_to "Destroy", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" }  %>